version: '3.7'

services:
  db:
    image: mysql:5.7.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laerciojunior
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql

  backend:
    container_name: backend
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes: 
      - ./php:/var/www/html
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080